// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lfewufpfqbylpssbncix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmZXd1ZnBmcWJ5bHBzc2JuY2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjc0ODAsImV4cCI6MjA2MzY0MzQ4MH0.7P3_Yg-C7iI8cLUkIW5Lb_Z24ltwNpUq2t-H9WxRyEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);